language: android
addons:
  apt:
    packages:
      - gcc
      - g++
before_script:
  - cd example/app/android
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 4
  - npm install -g npm@3.2
  - npm install -g appium
  - npm install
  # install boot
  - export PATH=~/bin:$PATH
  - export BOOT_VERSION=2.5.5
  - export BOOT_JVM_OPTIONS="-Xmx2g -client -XX:-OmitStackTraceInFastThrow -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:MaxPermSize=256m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xverify:none"

  - (mkdir ~/bin && cd ~/bin && curl -fsSLo boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh && chmod 755 boot)
  - boot -v
  - ./gradlew assembleDebug -PdisablePreDex -Pjobs=1 
  - android-wait-for-emulator
  - ./gradlew installDebug -PdisablePreDex -Pjobs=1 
  - adb shell input keyevent 82 &
script:
  - cd ../.. && ls
  - (cd .. && boot inst)
  - timeout 600 ./test-reloading.sh

