language: clojure
cache:
  directories:
  - $HOME/.m2
jdk:
    - oraclejdk8
install:
    - nvm install 4.0
    - wget -O boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
    - chmod 755 boot
    - ./boot -V 
    - (cd example/app && npm install)
script: ./boot inst && cd example && ../boot build && ../boot dist
sudo: false
