language: android
addons:
  apt:
    packages:
      - gcc
      - g++
      - automake #watchman
      - autoconf #watchman
before_script:
  - export TERM=dumb
  - . ./shell-helpers.sh
  - rm -rf ~/background && mkdir ~/background
  - cd example/app/android
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 4
  - npm config set progress=false
  - npm config set spin=false
  - npm install --no-optional
  # install boot
  - export PATH=~/bin:$PATH
  - export BOOT_VERSION=2.5.5
  - export BOOT_JVM_OPTIONS="-Xmx2g -client -XX:-OmitStackTraceInFastThrow -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:MaxPermSize=256m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xverify:none"

  - (mkdir ~/bin && cd ~/bin && curl -fsSLo boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh && chmod 755 boot)
  - run-bg "./gradlew assembleDebug -PdisablePreDex -Pjobs=1"
  - run-bg "npm install -g appium --no-optional "
  - (cd ../../.. && boot inst && ./watchman-install.sh && cd example && boot fast-build) &
  - run-with-timeout 600 wait-for-bg
  - run-with-timeout 600 wait-for-avd
  #using installDebug leads to timeout on Travis - see http://stackoverflow.com/questions/32952413/gradle-commands-fail-on-api-23-google-api-emulator-image-armeabi-v7a
  - adb install app/build/outputs/apk/app-debug.apk
  - adb shell input keyevent 82 &
script:
  - cd ../.. && ls
  - appium &
  - run-with-timeout 600 wait-for-url "http://localhost:8081/index.android.bundle?platform=android"
  - boot rn/print-android-log wait &
  - ./integration-tests.boot

